Repository Katchup-dev/Katchup-server, pull requests merged in 2023-08, with the labels that each got.

#87 [REFACTOR] Swagger 적용
  src/main/java/site/katchup/katchupserver/api/auth/controller/AuthController.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/response/AuthLoginResponseDto.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/response/AuthTokenGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/folder/dto/response/FolderGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/KeywordResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/request/KeywordCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/dto/MemberProfileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotUploadResponseDto.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/dto/request/TaskCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/task/dto/response/TaskGetResponseDto.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
  src/main/java/site/katchup/katchupserver/config/SwaggerConfig.java
Labels: documentation, 🐻 윤한 🐻

#93 [REFACTOR] security code 개선
  src/main/java/site/katchup/katchupserver/api/member/repository/MemberRepository.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtTokenProvider.java
Labels: 🐻 윤한 🐻, 🛠️Refactor🛠️

#95 [REFACTOR] Exception 처리 구조 변경
  src/main/java/site/katchup/katchupserver/api/auth/service/GoogleAuthService.java
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/common/CardProvider.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/exception/BadRequestException.java
  src/main/java/site/katchup/katchupserver/common/exception/BaseException.java
  src/main/java/site/katchup/katchupserver/common/exception/CustomException.java
  src/main/java/site/katchup/katchupserver/common/exception/EntityNotFoundException.java
  src/main/java/site/katchup/katchupserver/common/exception/InternalServerException.java
  src/main/java/site/katchup/katchupserver/common/exception/NotFoundException.java
  src/main/java/site/katchup/katchupserver/common/exception/UnauthorizedException.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/util/MemberUtil.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtTokenProvider.java
Labels: 🐼 예슬 🐼, 🛠️Refactor🛠️

#99 [REFACTOR] CardProvider 제거
  src/main/java/site/katchup/katchupserver/api/card/repository/CardRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/impl/KeywordServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/trash/domain/Trash.java
Labels: 🐻 윤한 🐻

#101 [REFACTOR] response body 구조 개선 및 단건 조회 로직 구현부 변경
  src/main/java/site/katchup/katchupserver/api/auth/controller/AuthController.java
  src/main/java/site/katchup/katchupserver/api/auth/service/GoogleAuthService.java
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/repository/CardRepository.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/repository/CategoryRepository.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/common/CardProvider.java
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/folder/dto/request/FolderCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/folder/dto/request/FolderUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/folder/repository/FolderRepository.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/repository/MemberRepository.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/repository/TaskRepository.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/exception/BadRequestException.java
  src/main/java/site/katchup/katchupserver/common/exception/BaseException.java
  src/main/java/site/katchup/katchupserver/common/exception/InternalServerException.java
  src/main/java/site/katchup/katchupserver/common/exception/NotFoundException.java
  src/main/java/site/katchup/katchupserver/common/exception/UnauthorizedException.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/common/util/MemberUtil.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtTokenProvider.java
Labels: 🐼 예슬 🐼, 🛠️Refactor🛠️

#104 [REFACTOR] 스크린샷 PreSigned-Url 방식 도입
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/request/ScreenshotCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/request/ScreenshotGetPreSignedRequestDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotUploadResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/repository/ScreenshotRepository.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotValidator.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
  src/main/java/site/katchup/katchupserver/config/AwsS3Config.java
  src/test/java/site/katchup/katchupserver/api/screenshot/domain/ScreenshotTest.java
Labels: 🐼 예슬 🐼, 🛠️Refactor🛠️

#109 [FIX] category 목록 조회 method 수정
  src/main/java/site/katchup/katchupserver/api/category/repository/CategoryRepository.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
Labels: 🐻 윤한 🐻, 🐞Fix🐞

#114 [ADD] 업무 카드 조회 시, 번호 스티커도 조회
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/request/ScreenshotCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/sticker/dto/request/StickerCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/sticker/dto/response/StickerGetResponseDto.java
Labels: 🐹 서경 🐹, ✨Feat✨

#113 [FIX] 업무 카드 생성 시, 세부 업무 작성 안하면 '기타' 업무로 분류 & 업무 내 키워드 목록 조회 로직 수정
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/subTask/repository/SubTaskRepository.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#116 [FIX] category, task, subTask id header로 응답
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/service/CategoryService.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/subTask/controller/SubTaskController.java
  src/main/java/site/katchup/katchupserver/api/subTask/service/Impl/SubTaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/subTask/service/SubTaskService.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/TaskService.java
Labels: 🐹 서경 🐹, 🐞Fix🐞

#119 [FEAT] 파일 PreSigned-Url 발급 API 개발
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/response/CardGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/repository/FileRepository.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/controller/FileController.java
  src/main/java/site/katchup/katchupserver/api/file/domain/File.java
  src/main/java/site/katchup/katchupserver/api/file/dto/request/FileCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/request/FileGetPreSignedRequestDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/repository/FileRepository.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/request/KeywordCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/link/domain/Link.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/task/dto/request/TaskCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/task/dto/request/TaskUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#121 [FIX] 파일 및 스크린샷 URL 저장 로직 수정
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/controller/FileController.java
  src/main/java/site/katchup/katchupserver/api/file/dto/request/FileCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/request/FileGetPreSignedRequestDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/KeywordService.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/impl/KeywordServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/request/ScreenshotCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/request/ScreenshotGetPreSignedRequestDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#125 [FIX] 업무 카드 & 업무 삭제 로직 오류 수정
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/repository/CategoryRepository.java
  src/main/java/site/katchup/katchupserver/api/subTask/repository/SubTaskRepository.java
  src/main/java/site/katchup/katchupserver/api/subTask/service/Impl/SubTaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/repository/TaskRepository.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/TaskService.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#124 [FEAT] 파일 & 스크린샷 삭제 API
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/controller/FileController.java
  src/main/java/site/katchup/katchupserver/api/file/domain/File.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
  src/main/java/site/katchup/katchupserver/config/WebMvcConfig.java
Labels: 🐹 서경 🐹, ✨Feat✨

#128 [FEAT] 파일명 자동 변경 시, 변경된 이름으로 파일 다운로드
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/controller/FileController.java
  src/main/java/site/katchup/katchupserver/api/file/domain/File.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetDownloadPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetUploadPreSignedResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#129 [FEAT] 업무 카드 수정 API
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/request/CardUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/CardKeywordRepository.java
Labels: 🐹 서경 🐹, ✨Feat✨

#131 [FIX] 업무 카드 생성 전, 파일 및 스크린샷 삭제 로직 수정
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/dto/response/CardListGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/controller/FileController.java
  src/main/java/site/katchup/katchupserver/api/file/domain/File.java
  src/main/java/site/katchup/katchupserver/api/file/dto/request/FileCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/file/repository/FileRepository.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#135 [FIX] 업무 카드 상세 조회 시, content와 note 값 누락된 버그 수정
  src/main/java/site/katchup/katchupserver/api/card/dto/response/CardGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#137 [FIX] 파일 및 스크린샷 업로드 날짜 저장
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/domain/File.java
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetResponseDto.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞

#138 [FIX] 업무 카드 조회 시 id 값들도 내려주도록 수정
  src/main/java/site/katchup/katchupserver/api/card/dto/response/CardGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞
