Repository Katchup-dev/Katchup-server, pull requests merged in 2023-10, with the labels that each got.

#154 [RENAME] 업무카드 수정 시 request의 필드명과 업무카드 조회 시 response의 필드명 통일
  src/main/java/site/katchup/katchupserver/api/file/dto/response/FileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetResponseDto.java
Labels: 🐹 서경 🐹, 🐞Fix🐞

#156 [FEAT] 소셜 로그아웃 api 구현
  src/main/java/site/katchup/katchupserver/api/auth/controller/AuthController.java
  src/main/java/site/katchup/katchupserver/api/auth/service/AuthService.java
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#157 [FEAT] 회원 탈퇴 API
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/repository/CategoryRepository.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/controller/WithdrawController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
  src/main/java/site/katchup/katchupserver/api/member/dto/request/MemberDeleteRequestDto.java
  src/main/java/site/katchup/katchupserver/api/member/dto/response/MemberProfileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/member/repository/WithdrawRepository.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/WithdrawServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/service/MemberService.java
  src/main/java/site/katchup/katchupserver/api/member/service/WithdrawService.java
Labels: 🐹 서경 🐹, ✨Feat✨

#162 [FEAT] 카테고리별 공유 활성화 토글 변경 api
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/domain/Category.java
  src/main/java/site/katchup/katchupserver/api/category/dto/response/CategoryPatchSharedStatusResponseDto.java
  src/main/java/site/katchup/katchupserver/api/category/service/CategoryService.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#166 [REFACTOR] S3 구조 수정
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/external/s3/AwsS3Config.java
  src/main/java/site/katchup/katchupserver/external/s3/PreSignedUrlVO.java
  src/main/java/site/katchup/katchupserver/external/s3/S3Service.java
Labels: 🐻 윤한 🐻, ✨Feat✨

#170 [REFACTOR] 기존 AWS 의존성 교체 및 코드 리팩토링
  build.gradle
  src/main/java/site/katchup/katchupserver/api/file/service/Impl/FileServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/external/s3/AWSConfig.java
  src/main/java/site/katchup/katchupserver/external/s3/AwsS3Config.java
  src/main/java/site/katchup/katchupserver/external/s3/DownloadPreSignedUrlVO.java
  src/main/java/site/katchup/katchupserver/external/s3/S3Service.java
Labels: 🐻 윤한 🐻, 🛠️Refactor🛠️

#171 [ADD] 업무 카드 조회 시, screenshotName도 조회
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/file/service/FileService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
Labels: 🐹 서경 🐹, 🛠️Refactor🛠️, ⚡️ADD⚡️

#175 [CHORE] withdraw table 변경
  src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
  src/main/java/site/katchup/katchupserver/api/member/dto/request/MemberDeleteRequestDto.java
  src/main/java/site/katchup/katchupserver/common/util/StringListConverter.java
Labels: 🐹 서경 🐹, 🖇Chore🖇

#176 [FEAT] 프로필 수정 API 개발
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/domain/MemberProfile.java
  src/main/java/site/katchup/katchupserver/api/member/dto/request/MemberProfileUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/member/dto/response/MemberProfileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/service/MemberService.java
  src/main/java/site/katchup/katchupserver/external/s3/AWSConfig.java
  src/main/java/site/katchup/katchupserver/external/s3/S3Service.java
  src/test/java/site/katchup/katchupserver/api/member/domain/MemberTest.java
Labels: 🐻 윤한 🐻, 🐞Fix🐞, ⚡️ADD⚡️

#184 [REFACTOR] 프로필 정보 설정 API 리팩토링
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/domain/MemberProfile.java
  src/main/java/site/katchup/katchupserver/api/member/dto/request/MemberProfileUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/member/dto/response/MemberProfileGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorCode.java
Labels: 🐻 윤한 🐻, 🛠️Refactor🛠️
