Repository Katchup-dev/Katchup-server, pull requests merged in 2023-05, with the labels that each got.

#3 [CONFIG] AWS S3 설정
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
  src/main/java/site/katchup/katchupserver/config/AwsS3Config.java
  src/main/java/site/katchup/katchupserver/config/JpaQueryFactoryConfig.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
Labels: 🐻 윤한 🐻, ⚙️Config⚙️

#8 [FIX] s3 Util 잘못된 선언 해결
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
Labels: 🐞Fix🐞

#9 #2 [FEAT] Entity 개발
  build.gradle
  src/main/java/site/katchup/katchupserver/KatchupserverApplication.java
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/card/domain/File.java
  src/main/java/site/katchup/katchupserver/api/card/repository/CardRepository.java
  src/main/java/site/katchup/katchupserver/api/category/domain/Category.java
  src/main/java/site/katchup/katchupserver/api/folder/domain/Folder.java
  src/main/java/site/katchup/katchupserver/api/folder/repository/FolderRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/domain/Keyword.java
  src/main/java/site/katchup/katchupserver/api/keyword/domain/TaskKeyword.java
  src/main/java/site/katchup/katchupserver/api/link/domain/Link.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Withdraw.java
  src/main/java/site/katchup/katchupserver/api/member/repository/MemberRepository.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/repository/ScreenshotRepository.java
  src/main/java/site/katchup/katchupserver/api/task/domain/Task.java
  src/main/java/site/katchup/katchupserver/api/task/repository/TaskRepository.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/domain/BaseEntity.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
  src/main/java/site/katchup/katchupserver/config/JpaAuditingConfig.java
  src/main/java/site/katchup/katchupserver/config/TimezoneConfig.java
  src/test/java/site/katchup/katchupserver/KatchupserverApplicationTests.java
  src/test/java/site/katchup/katchupserver/api/card/domain/CardTest.java
  src/test/java/site/katchup/katchupserver/api/member/domain/MemberTest.java
  src/test/java/site/katchup/katchupserver/api/screenshot/domain/ScreenshotTest.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#11 [CONFIG] dependabot 추가
  .github/dependabot.yml
Labels: 🐻 윤한 🐻, ⚙️Config⚙️

#10 [CONFIG] CI & CD
  .github/workflows/pr-build-deploy.yml
  Dockerfile
  src/test/java/site/katchup/katchupserver/KatchupserverApplicationTests.java
Labels: 🐻 윤한 🐻, ✨Feat✨

#14 [Fix] Card, Screenshot 테이블의 index 필드명 변경
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/test/java/site/katchup/katchupserver/api/card/domain/CardTest.java
  src/test/java/site/katchup/katchupserver/api/screenshot/domain/ScreenshotTest.java
Labels: 🐹 서경 🐹, 🐞Fix🐞, ✏️Rename✏️

#17 [FEAT] 구글 소셜 로그인 & 회원가입
  build.gradle
  src/main/java/site/katchup/katchupserver/api/auth/controller/AuthController.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/AuthRequestDto.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/AuthResponseDto.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/GoogleInfoDto.java
  src/main/java/site/katchup/katchupserver/api/auth/service/AuthService.java
  src/main/java/site/katchup/katchupserver/api/auth/service/GoogleAuthService.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/repository/MemberRepository.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/exception/CustomException.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtExceptionType.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtTokenProvider.java
  src/main/java/site/katchup/katchupserver/config/jwt/UserAuthentication.java
Labels: 🐹 서경 🐹, ✨Feat✨

#24 [FEAT] 프로필 팝업 조회
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/dto/MemberResponseDto.java
  src/main/java/site/katchup/katchupserver/api/member/service/MemberService.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
Labels: 🐹 서경 🐹, ✨Feat✨

#25 #22 [FEAT] 대분류 카테고리 전체 목록 조회 API
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/dto/response/CategoryResponseDto.java
  src/main/java/site/katchup/katchupserver/api/category/repository/CategoryRepository.java
  src/main/java/site/katchup/katchupserver/api/category/service/CategoryService.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#27 [FEAT] 중분류 폴더 전체 목록 조회 API
  .gitignore
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/folder/dto/response/FolderResponseDto.java
  src/main/java/site/katchup/katchupserver/api/folder/repository/FolderRepository.java
  src/main/java/site/katchup/katchupserver/api/folder/service/FolderService.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#32 [FEAT] 업무 소분류 목록 조회
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/dto/TaskResponseDto.java
  src/main/java/site/katchup/katchupserver/api/task/repository/TaskRepository.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/TaskService.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐹 서경 🐹, ✨Feat✨

#34 [FEAT] 특정 카테고리 내 중분류 폴더 조회 API
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/folder/service/FolderService.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#36 [REFACTOR] getMemberId 메소드 MemberUtil 클래스로 분리
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/dto/response/CategoryResponseDto.java
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/common/util/MemberUtil.java
Labels: 🐼 예슬 🐼, 🛠️Refactor🛠️

#40 [FEAT] 스크린샷 추가 API
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/UploadScreenshotResponseDTO.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotValidator.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/common/util/S3Util.java
  src/test/java/site/katchup/katchupserver/api/screenshot/domain/ScreenshotTest.java
Labels: 🐻 윤한 🐻, ✨Feat✨

#41 [FEAT] 업무 소분류 추가 API
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
  src/main/java/site/katchup/katchupserver/api/task/dto/TaskCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/TaskService.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐹 서경 🐹, ✨Feat✨

#47 [FEAT] 키워드 목록 조회 API
  src/main/java/site/katchup/katchupserver/api/card/repository/CardRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/KeywordResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/KeywordRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/TaskKeywordRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/KeywordService.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/impl/KeywordServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/task/service/Impl/TaskServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐹 서경 🐹, ✨Feat✨

#44 [FEAT] 토큰 재발급 API
  build.gradle
  src/main/java/site/katchup/katchupserver/api/auth/controller/AuthController.java
  src/main/java/site/katchup/katchupserver/api/auth/dto/AuthTokenResponseDto.java
  src/main/java/site/katchup/katchupserver/api/auth/service/AuthService.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/repository/MemberRepository.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/main/java/site/katchup/katchupserver/config/SecurityConfig.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtAuthenticationFilter.java
  src/main/java/site/katchup/katchupserver/config/jwt/JwtTokenProvider.java
Labels: 🐹 서경 🐹, ✨Feat✨

#48 [FEAT] 키워드 추가 API
  src/main/java/site/katchup/katchupserver/api/keyword/controller/KeywordController.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/KeywordCreateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/KeywordService.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/impl/KeywordServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/exception/EntityNotFoundException.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐹 서경 🐹, ✨Feat✨

#53 [FEAT] 업무 카드 삭제 API
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/card/dto/CardDeleteRequestDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/CardResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/repository/CardRepository.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/common/CardProvider.java
  src/main/java/site/katchup/katchupserver/api/keyword/domain/CardKeyword.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/KeywordResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/CardKeywordRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/TaskKeywordRepository.java
  src/main/java/site/katchup/katchupserver/api/keyword/service/impl/KeywordServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/screenshot/domain/Screenshot.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/trash/domain/Trash.java
  src/main/java/site/katchup/katchupserver/api/trash/repository/TrashRepository.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
  src/test/java/site/katchup/katchupserver/api/card/domain/CardTest.java
  src/test/java/site/katchup/katchupserver/api/screenshot/domain/ScreenshotTest.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#56 [ADD] 업무 카드 조회 시, 파일 유무 값 추가
  src/main/java/site/katchup/katchupserver/api/card/dto/CardResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/domain/CardKeyword.java
  src/main/java/site/katchup/katchupserver/api/keyword/domain/Keyword.java
Labels: 🐼 예슬 🐼, ⚡️ADD⚡️

#57 [FEAT] 업무 대분류명 수정 API
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/category/domain/Category.java
  src/main/java/site/katchup/katchupserver/api/category/dto/request/CategoryUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/category/service/CategoryService.java
  src/main/java/site/katchup/katchupserver/api/category/service/Impl/CategoryServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#49 [FEAT] 스크린 샷 삭제 API 구현
  src/main/java/site/katchup/katchupserver/api/screenshot/controller/ScreenshotController.java
  src/main/java/site/katchup/katchupserver/api/screenshot/repository/ScreenshotRepository.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/dto/ApiResponseDto.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐻 윤한 🐻, ✨Feat✨

#66 [REFACTOR] auth, member 도메인 ServiceImpl로 리팩토링
  src/main/java/site/katchup/katchupserver/api/auth/dto/GoogleInfoDto.java
  src/main/java/site/katchup/katchupserver/api/auth/service/AuthService.java
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/controller/MemberController.java
  src/main/java/site/katchup/katchupserver/api/member/domain/Member.java
  src/main/java/site/katchup/katchupserver/api/member/service/Impl/MemberServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/member/service/MemberService.java
  src/main/java/site/katchup/katchupserver/api/task/controller/TaskController.java
Labels: 🐹 서경 🐹, 🛠️Refactor🛠️

#61 [FEAT] 업무 중분류명 수정 API
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
  src/main/java/site/katchup/katchupserver/api/folder/controller/FolderController.java
  src/main/java/site/katchup/katchupserver/api/folder/domain/Folder.java
  src/main/java/site/katchup/katchupserver/api/folder/dto/request/FolderUpdateRequestDto.java
  src/main/java/site/katchup/katchupserver/api/folder/repository/FolderRepository.java
  src/main/java/site/katchup/katchupserver/api/folder/service/FolderService.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/advice/ControllerExceptionAdvice.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐼 예슬 🐼, ✨Feat✨

#58 [FEAT] 업무 카드 상세조회 API 구현
  src/main/java/site/katchup/katchupserver/api/card/controller/CardController.java
  src/main/java/site/katchup/katchupserver/api/card/domain/Card.java
  src/main/java/site/katchup/katchupserver/api/card/domain/File.java
  src/main/java/site/katchup/katchupserver/api/card/dto/CardGetResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/CardResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/dto/FileResponseDto.java
  src/main/java/site/katchup/katchupserver/api/card/repository/FileRepository.java
  src/main/java/site/katchup/katchupserver/api/card/service/CardService.java
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/folder/repository/FolderRepository.java
  src/main/java/site/katchup/katchupserver/api/folder/service/Impl/FolderServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/keyword/dto/KeywordResponseDto.java
  src/main/java/site/katchup/katchupserver/api/keyword/repository/KeywordRepository.java
  src/main/java/site/katchup/katchupserver/api/screenshot/dto/response/ScreenshotResponseDto.java
  src/main/java/site/katchup/katchupserver/api/screenshot/repository/ScreenshotRepository.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/ScreenshotService.java
  src/main/java/site/katchup/katchupserver/api/screenshot/service/impl/ScreenshotServiceImpl.java
  src/main/java/site/katchup/katchupserver/common/response/ErrorStatus.java
  src/main/java/site/katchup/katchupserver/common/response/SuccessStatus.java
Labels: 🐻 윤한 🐻, ✨Feat✨

#76 [ADD] Cors 설정
  src/main/java/site/katchup/katchupserver/config/WebMvcConfig.java
Labels: 🐹 서경 🐹, 🐞Fix🐞
