Repository Katchup-dev/Katchup-server, pull requests merged in 2023-11, with the labels that each got.

#199 [SETTING] 설정 파일 수정
  .github/workflows/ci-cd.yml
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: 🐻 윤한 🐻, ⚙️Config⚙️

#200 [Fix] 업무카드 수정 API
  src/main/java/site/katchup/katchupserver/api/card/service/Impl/CardServiceImpl.java
  src/main/java/site/katchup/katchupserver/external/s3/AWSConfig.java
  src/main/java/site/katchup/katchupserver/external/s3/S3Service.java
Labels: 🐻 윤한 🐻, 🐞Fix🐞

#203 [FIX] 공유용 출력 뷰에서 공유한 유저가 작성한 카테고리 목록을 조회할 수 있도록 수정
  src/main/java/site/katchup/katchupserver/api/auth/dto/response/AuthLoginResponseDto.java
  src/main/java/site/katchup/katchupserver/api/auth/service/Impl/AuthServiceImpl.java
  src/main/java/site/katchup/katchupserver/api/category/controller/CategoryController.java
Labels: 🐼 예슬 🐼, 🐞Fix🐞
